export const demoComponents = [
  "accordion-demo",
  "alertdialog-demo",
  "animatedbutton-demo",
  "animatedshowcase-demo",
  "aspectratio-demo",
  "avatar-demo",
  "badge-demo",
  "badge-destructive",
  "badge-secondary",
  "badge-outline",
  "button-demo",
  "card-demo",
  "dropdownnotifications-demo",
  "dropdownuser-demo",
  "glowingbordercard-demo",
  "interactiveinput-demo",
  "lamphome-demo",
  "lighttrail-demo",
  "lustretext-demo",
  "magicdock-demo",
  "profilecard-demo",
  "spotlightcard-demo",
  "themeswitch-demo",
  "thswitchhideinactive",
  "thswitchstdall",
  "thswitchtwonext",
  "thswitchthreenext",
  "thsinglecentredtwo",
  "thsinglecentredthree",
  // Add more demo components here
] as const;

export type DemoComponentKeys = (typeof demoComponents)[number];
