export const demoComponents = [
  "accordion-demo",
  "alertdialog-demo",
  "animatedbutton-demo",
  "animatedshowcase-demo",
  "aspectratio-demo",
  "avatar-demo",
  "badge-demo",
  "badge-destructive",
  "badge-secondary",
  "badge-outline",
  "button-demo",
  "card-demo",
  "carousel-demo",
  "carouselimage-demo",
  "dropdownuser-demo",
  "dropdownnotifications-demo",
  "followcursor-demo",
  "glowingbordercard-demo",
  "interactiveinput-demo",
  "lamphome-demo",
  "lighttrail-demo",
  "lustretext-demo",
  "magicdock-demo",
  "pagination-demo",
  "profilecard-demo",
  "spotlightcard-demo",
  "seperatorpro-demo",
  "seperatorprodotted",
  "seperatorprowavy",
  "themeswitch-demo",
  "thswitchhideinactive",
  "thswitchstdall",
  "thswitchtwonext",
  "thswitchthreenext",
  "thsinglecentredtwo",
  "thsinglecentredthree",
  "toastaddtocart-demo",
  "toastdelete-demo",
  "toasterror-demo",
  "toastinfo-demo",
  "toastdefault-demo",
  "toastwarning-demo",
  "toastsuccess-demo",
  // Add more demo components here
] as const;

export type DemoComponentKeys = (typeof demoComponents)[number];
