export const parentComponents = [
  "accordion",
  "alert-dialog",
  "animated-button",
  "animated-showcase",
  "aspect-ratio",
  "avatar",
  "badge",
  "button",
  "card",
  "carousel",
  "dropdown",
  "followcursor",
  "glowingbordercard",
  "interactive-input",
  "lamphome",
  "light-trail",
  "lustretext",
  "magicdock",
  "pagination",
  "particles",
  "profilecard",
  "radialflow",
  "spotlightcard",
  "seperatorpro",
  "theme-switch",
  "toast",
  // Add more parent component names here
] as const;

export type ParentComponentKeys = (typeof parentComponents)[number];
