import { a } from "@react-spring/web";

export const parentComponents = [
  "accordion",
  "alert-dialog",
  "animated-button",
  "animated-testimonials",
  "animated-textgenerate",
  "animated-tabs",
  "aspect-ratio",
  "avatar",
  "backgroundmeteors",
  "background-paths",
  "badge",
  "beams-upstream",
  "border-glide",
  "button",
  "card",
  "carousel",
  "codeblock",
  "cursorimagetrail",
  "cursor-highlight",
  "dropdown-menu",
  "expandable-dock",
  "flipstack",
  "followcursor",
  "flowing-logos",
  "glowingbordercard",
  "globe",
  "gravity",
  "heroui",
  "hold-toconfirm",
  "input-otp",
  "interactive-input",
  "kinetic-testimonials",
  "lamphome",
  "loader",
  "lustretext",
  "magicdock",
  "motioncards",
  "morphotextflip",
  "not-found",
  "navbar-flow",
  "pagination",
  "parallaxcards",
  "particles",
  "profilecard",
  "radialflow",
  "radial-socials",
  "side-sheet",
  "stagger-chars",
  "statscount",
  "statscarousel",
  "splitter",
  "spotlightcard",
  "seperatorpro",
  "scroll-areapro",
  "table",
  "text-highlighter",
  "theme-switch",
  "top-sheet",
  "toast",
  "toggle-vault",
  "typeanimation",
  "venom-beam",
  "whitestripes",
  // Add more parent component names here
] as const;

export type ParentComponentKeys = (typeof parentComponents)[number];
